In [56]:
# from scipy.optimize import fsolve

import plotly.graph_objects as go
# import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

In [57]:
# Задаем исходные данные 
x = np.array([-0.6, -0.4, -0.2, 0.0, 0.2, 0.4])
y = np.array([-1.06, -1.406, -0.386, 1, 1.386, 0.406])

degrees = [1, 2, 3, 4, 5] 

pd.DataFrame(data=(x, y), index = ['x', 'y'])

0      1      2    3      4      5
x -0.60 -0.400 -0.200  0.0  0.200  0.400
y -1.06 -1.406 -0.386  1.0  1.386  0.406

In [58]:
fig = go.Figure() # layout_xaxis_range = [-2,6]
fig.add_trace(go.Scatter(x=x,
                         y=y,
                         mode='markers',
                         marker=dict(color='LightSkyBlue', size=15, line=dict(color='MediumPurple', width=3)),
                         name="Исходные данные"))

for degree in degrees: 
    coefficients = np.polyfit(x, y, degree) 
    poly = np.poly1d(coefficients) 
    print(coefficients)
    print(poly)
 
    # Генерируем значения для построения графика 
    x_plot = np.linspace(x.min(), x.max(), 100) 
    y_plot = poly(x_plot) 
 
    # Вычисляем среднеквадратичное отклонение 
    y_pred = poly(x) 
    sko = np.sqrt(np.mean((y - y_pred) ** 2)) 
 
    # Строим график и выводим sko 
    fig.add_trace(go.Scatter(x=x_plot,
                             y=y_plot,
                             name=f'Степень {degree}, СКО: {sko:.2f}'))


fig.update_layout(title="Построение графика аппроксимирующих полиномов",
                  xaxis_title="Значение аргумента",
                  yaxis_title="Значение полинома",
                  margin=dict(l=10, r=70, t=50, b=0))


[2.44171429 0.23417143]
 
2.442 x + 0.2342
[-2.54732143  1.93225     0.50588571]
        2
-2.547 x + 1.932 x + 0.5059
[-20.55324074  -8.71329365   5.46740741   0.90050794]
        3         2
-20.55 x - 8.713 x + 5.467 x + 0.9005
[  8.25520833 -17.25115741 -10.45868056   5.05228836   0.94579365]
       4         3         2
8.255 x - 17.25 x - 10.46 x + 5.052 x + 0.9458
[ 35.57291667  26.04166667 -25.15625    -13.54166667   5.37933333
   1.        ]
       5         4         3         2
35.57 x + 26.04 x - 25.16 x - 13.54 x + 5.379 x + 1
